// class that will request the artist's album information from API or return previously received data 
using System.Text.Json;

namespace ArtistPages
{
    public class ArtistLatestRelease
    {
        private Dictionary<string, ArtistTrack> artistTrackCache;
        private DateTime refreshTime;
        private ArtistList artistList = new ArtistList();

        private readonly TokenManager _tokenManager;

        public ArtistLatestRelease(TokenManager tokenManager)
        {
            _tokenManager = tokenManager;
            artistTrackCache = new Dictionary<string, ArtistTrack>();
        }

        //given artist id from artist list and accesstoken generated by TokenManager
        private static async Task<string> GetArtistInfoAsync(string artistId, string accessToken)
        {
            string url = $"https://api.spotify.com/v1/artists/{artistId}/albums";

            using (var client = new HttpClient()) //creates a new http client that closes when finished
            {
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);

                var response = await client.GetAsync(url); //requests information using the url after authorization by access token
                if (!response.IsSuccessStatusCode) // will throw an exception of the API does not return with a valid response
                {
                    throw new HttpRequestException($"Request failed with status code {response.StatusCode}");
                }

                var responseContent = await response.Content.ReadAsStringAsync();
                return responseContent; //returns a json string
            }
        }

        private async Task<ArtistTrack> GenerateArtistInfo(string artistId)
        {
            Console.Out.WriteLine($"Receiving Artist Data for ID: {artistId}\n");
            string accessToken = await _tokenManager.get_token();
            string artistInfoJson = await GetArtistInfoAsync(artistId, accessToken);// initiates the request to the API
            return JsonSerializer.Deserialize<ArtistTrack>(artistInfoJson); //places the response into the ArtistTrackData class
        }

        public async Task<ArtistTrack> GetArtistInfo(string artistId)
        {
            // at startup will make a request for first information from API
            //when artistalbum info is requested will check and see if it should get refreshed information
            if (!artistTrackCache.ContainsKey(artistId) || DateTime.UtcNow >= refreshTime)
            {
                await Console.Out.WriteLineAsync("Album Data Expired Refreshing");
                artistTrackCache[artistId] = await GenerateArtistInfo(artistId);
                //sets a refresh timer of 15 mins to limit calls to API
                refreshTime = DateTime.UtcNow.AddSeconds(900);
                await Console.Out.WriteLineAsync("Received Data at: " + DateTime.UtcNow);
                await Console.Out.WriteLineAsync("Next Refresh at: " + refreshTime + "\n");
            }
            //returns the valid artist album information for a specific artist
            return artistTrackCache[artistId];
        }
    }
}
